{{- if .Values.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | default .Release.Name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.name | default .Release.Name }}
  ports:
    {{- if .Values.servicePorts }}
    {{- range .Values.servicePorts }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
    {{- else }}
    {{- range .Values.ports }}
    - port: {{ . }}
      targetPort: {{ . }}
    {{- end }}
    {{- end }}
{{- end }}
