{
  "services": {
    "grafana": {
      "container_name": "grafana",
      "image": "grafana/grafana:latest",
      "restart": "unless-stopped",
      "ports": [
        "3000:3000"
      ],
      "volumes": [
        "/mnt/core_data/grafana:/var/lib/grafana",
        "/opt/docker-secrets/grafana/grafana_password:/run/secrets/grafana_password:ro",
        "/opt/docker/grafana/grafana.ini:/etc/grafana/grafana.ini:ro"
      ],
      "environment": {
        "GF_SECURITY_ADMIN_PASSWORD__FILE": "/run/secrets/grafana_password"
      }
    }
  }
}
