apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- if .Values.podDnsConfig.nameservers }}
      dnsConfig:
        nameservers:
{{ toYaml .Values.podDnsConfig.nameservers | indent 10 }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.args }}
          args:
{{ toYaml .Values.image.args | indent 12 }}
          {{- end }}
          {{- if .Values.containerPorts }}
          ports:
{{ toYaml .Values.containerPorts | indent 12 }}
          {{- end }}
          {{- if .Values.env }}
          env:
{{ toYaml .Values.env | indent 12 }}
          {{- end }}
          securityContext:
            runAsUser: {{ .Values.runAsUser }}
            {{ if .Values.containerSecurityContext }}
{{ toYaml .Values.containerSecurityContext | indent 12 }}
            {{ end }}
          {{- if or .Values.volumes .Values.configMounts }}
          volumeMounts:
          {{- range .Values.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .readOnly }}
              readOnly: true
              {{- end }}
          {{- end }}
          {{- range .Values.configMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
              {{- if .readOnly }}
              readOnly: true
              {{- end }}
          {{- end }}
          {{- if .Values.secrets.enabled }}
            - name: application-secrets
              mountPath: /run/secrets
              readOnly: true
          {{- end }}
          {{- end }}
      {{- if or .Values.volumes .Values.configMounts .Values.secrets.enabled }}
      volumes:
      {{- range .Values.volumes }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
            type: {{ .type | default "DirectoryOrCreate" }}
      {{- end }}
      {{- range .Values.configMounts }}
        - name: {{ .name }}
          configMap:
            name: {{ .configMap }}
      {{- end }}
      {{- if .Values.secrets.enabled }}
        - name: application-secrets
          secret:
            secretName: {{ .Values.secrets.name }}
            optional: true
            defaultMode: 0400
      {{- end }}
      {{- end }}
