{
  "name": "sonarqube",
  "namespace": "sonarqube",
  "replicas": 1,
  "image": {
    "repository": "sonarqube",
    "tag": "lts-community",
    "pullPolicy": "IfNotPresent"
  },
  "service": {
    "type": "ClusterIP"
  },
  "ports": [
    9000
  ],
  "servicePorts": [
    {
      "name": "web",
      "port": 9000,
      "targetPort": 9000
    }
  ],
  "containerPorts": [
    {
      "containerPort": 9000,
      "protocol": "TCP"
    }
  ],
  "env": [],
  "runAsUser": 1000,
  "volumes": [
    {
      "name": "data",
      "hostPath": "/mnt/core_data/sonarqube/data",
      "mountPath": "/opt/sonarqube/data"
    },
    {
      "name": "extensions",
      "hostPath": "/mnt/core_data/sonarqube/extensions",
      "mountPath": "/opt/sonarqube/extensions"
    },
    {
      "name": "logs",
      "hostPath": "/mnt/core_data/sonarqube/logs",
      "mountPath": "/opt/sonarqube/logs"
    }
  ],
  "hostNetwork": false,
  "configMounts": [],
  "configMaps": [],
  "ingress": {
    "hosts": []
  },
  "secrets": {
    "enabled": false,
    "name": "sonarqube-secrets"
  }
}
