{
  "common": {
    "image": "prom/prometheus:latest",
    "port": "9090",
    "configFile": "config/prometheus.yml",
    "dataPath": "/mnt/core_data/prometheus"
  },
  "docker": {},
  "k3s": {
    "ingressHost": "",
    "ingressEnabled": "false"
  }
}
