{
  "services": {
    "proxy": {
      "container_name": "proxy",
      "image": "jc21/nginx-proxy-manager:latest",
      "restart": "unless-stopped",
      "ports": [
        "80:80",
        "443:443",
        "81:81"
      ],
      "volumes": [
        "/mnt/core_data/proxy:/data",
        "/mnt/core_data/proxy/letsencrypt:/etc/letsencrypt"
      ],
      "environment": {
        "DB_SQLITE_FILE": "/data/database.sqlite"
      },
      "networks": [
        "proxy"
      ],
      "dns": [
        "192.168.0.2",
        "192.168.0.3"
      ]
    }
  },
  "networks": {
    "proxy": {
      "external": true
    }
  }
}
