name: jenkins
namespace: jenkins
replicas: 1

image:
  repository: jenkins/jenkins
  tag: lts-jdk17
  pullPolicy: Always

service:
  type: ClusterIP

ports:
  - 8080
  - 50000

runAsUser: 0

env:
  - name: TZ
    value: Europe/Warsaw

volumes:
  - name: jenkins-home
    hostPath: /mnt/core_data/docker/jenkins_home
    mountPath: /var/jenkins_home

configMounts:

configMaps:

ingress:
  hosts:
    - domain: jenkins.ravcube.com
      port: 8080
