@Library('jenkins_shared_lib') _

pipeline {
    agent { label 'k3s' }
    options {
        skipDefaultCheckout();
        timestamps();
        ansiColor('xterm')
    }
    environment {
        CREDITS_ID = 'github-token'
        SERVICE_NAME = 'nexus'
    }
    stages {
        stage('Init ENV') {
            steps { script { initEnv() } }
        }
        stage('Checkout') {
            steps { checkoutBranch("${env.BRANCH}") }
        }
        stage('Init') {
            parallel {
                stage('Init Submodules') {
                    steps { script { initSubmodules() } }
                }
                stage('Init K3s config') {
                    steps { script { configureK3s() } }
                }
            }
        }
        stage('Test Lint') {
            steps { sh 'helm lint ./helm -f config.yml' }
        }
        stage('Template Test') {
            steps { sh 'helm template ./helm -f config.yml' }
        }
        stage('Dry Run Test') {
            steps {
                sh '''
                    helm upgrade --install ${SERVICE_NAME} ./helm \
                        -f config.yml \
                        --kubeconfig kubeconfig.yaml \
                        --dry-run --debug
                '''
            }
        }
    }
}
