{
  "name": "grafana",
  "namespace": "grafana",
  "replicas": 1,
  "image": {
    "repository": "grafana/grafana",
    "tag": "latest",
    "pullPolicy": "IfNotPresent"
  },
  "service": {
    "type": "ClusterIP"
  },
  "ports": [
    3000
  ],
  "servicePorts": [
    {
      "name": "web",
      "port": 3000,
      "targetPort": 3000
    }
  ],
  "containerPorts": [
    {
      "containerPort": 3000,
      "protocol": "TCP"
    }
  ],
  "env": [
    {
      "name": "GF_SECURITY_ADMIN_PASSWORD__FILE",
      "value": "/run/secrets/grafana_password"
    }
  ],
  "runAsUser": 472,
  "volumes": [
    {
      "name": "data",
      "hostPath": "/mnt/core_data/grafana",
      "mountPath": "/var/lib/grafana"
    }
  ],
  "hostNetwork": false,
  "configMounts": [
    {
      "name": "grafana-config",
      "configMap": "grafana-config",
      "mountPath": "/etc/grafana/grafana.ini",
      "subPath": "grafana.ini",
      "readOnly": true
    }
  ],
  "configMaps": [
    {
      "name": "grafana",
      "path": "config/grafana.ini"
    }
  ],
  "ingress": {
    "hosts": []
  },
  "secrets": {
    "enabled": true,
    "name": "grafana-secrets"
  }
}
