pipeline {
    agent {
        label 'home'
    }
    options {
        skipDefaultCheckout();
        timestamps();
        ansiColor('xterm')
    }
    environment {
        REPO_URL = 'https://github.com/KNOSERO/docker_services.git'
        DEFAULT_BRANCH = 'master'
        CREDITS_ID = 'github-token'
        SECRET_WEBHOOK = 'github-secret-webhook'
        ACCOUNT = 'KNOSERO'
        REPO = 'docker_service'
        PIPELINE_NAME = 'docker_service_validate'
        DOCKER_BUILDKIT = '1'
    }

    triggers {
        GenericTrigger(
            genericVariables: [
                [key: 'PR_ACTION', value: '$.action',                 expressionType: 'JSONPath', defaultValue: ''],
                [key: 'PR_NUMBER', value: '$.number',                 expressionType: 'JSONPath', defaultValue: ''],
                [key: 'PR_SHA',    value: '$.pull_request.head.sha',  expressionType: 'JSONPath', defaultValue: '']
            ],
            printContributedVariables: true,
            printPostContent: false,

            regexpFilterText: '$PR_ACTION',
            regexpFilterExpression: 'opened|reopened|synchronize'
        )
    }
    stages {
        stage('Checkout PR') {
            when { expression { env.PR_ACTION == 'opened' && env.PR_NUMBER || env.PR_ACTION == 'reopened' && env.PR_NUMBER || env.PR_ACTION == 'synchronize' && env.PR_NUMBER } }
            steps {
                script {
                    checkout([$class: 'GitSCM',
                        userRemoteConfigs: [[
                            name: 'origin',
                            url: env.REPO_URL,
                            credentialsId: env.CREDITS_ID,
                            refspec: '+refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/*'
                        ]],
                        branches: [[ name: "origin/pr/${env.PR_NUMBER}/merge" ]],
                        extensions: [
                            [$class: 'CloneOption', shallow: true, depth: 25, noTags: true, timeout: 240],
                            [$class: 'PruneStaleBranch']
                        ]
                    ])
                    def sha = env.PR_SHA?.trim() ? env.PR_SHA : env.CHECKOUT_SHA
                    if (sha?.trim()) {
                        githubNotify credentialsId: env.CREDITS_ID,
                                     account: env.ACCOUNT,
                                     repo: env.REPO,
                                     sha: "${sha}",
                                     context: env.PIPELINE_NAME,
                                     status: 'PENDING',
                                     description: 'Pipeline started'
                    }
                }
            }
        }

        stage('Checkout Manual') {
            when { not { expression { env.PR_ACTION == 'opened' || env.PR_ACTION == 'reopened' || env.PR_ACTION == 'synchronize' } } }
            steps {
                checkout([$class: 'GitSCM',
                    userRemoteConfigs: [[
                        name: 'origin',
                        url: env.REPO_URL,
                        credentialsId: env.CREDITS_ID,
                        refspec: '+refs/heads/*:refs/remotes/origin/*'
                    ]],
                    branches: [[ name: "*/${env.DEFAULT_BRANCH}" ]],
                    extensions: [
                        [$class:'CloneOption', shallow:true, depth:25, noTags:true, timeout:240],
                        [$class:'PruneStaleBranch']
                    ]
                ])
            }
        }

        stage('Init Submodules') {
            steps {
                script {
                    sh '''
                        git config --global url."https://github.com/".insteadOf "git@github.com:"
                        git submodule sync --recursive
                        git submodule update --init --recursive
                    '''
                }
            }
        }

        stage('Test Docker Compose') {
            steps {
                script {
                    sh '''
                        bash ./script/validate_docker.sh
                    '''
                }
            }
        }

        stage('Test Docker Compose') {
            steps {
                script {
                    sh '''
                        export DOCKER_HOST=tcp://home.ravnet:2375

                        KUBE_VERSION=1.29.0 STRICT=1 STRICT_CRD=0 SUMMARY=1 bash ./script/validate_kubernetes.sh
                    '''
                }
            }
        }
    }
    post {
        success {
            script {
                def sha = env.PR_SHA?.trim() ? env.PR_SHA : env.CHECKOUT_SHA
                if (sha?.trim()) {
                    githubNotify credentialsId: env.CREDITS_ID,
                                 account: env.ACCOUNT,
                                 repo: env.REPO,
                                 sha: "${sha}",
                                 context: env.PIPELINE_NAME,
                                 status: 'SUCCESS',
                                 description: 'All stages passed ✅'
                }
            }
        }
        failure {
            script {
                def sha = env.PR_SHA?.trim() ? env.PR_SHA : env.CHECKOUT_SHA
                if (sha?.trim()) {
                    githubNotify credentialsId: env.CREDITS_ID,
                                 account: env.ACCOUNT,
                                 repo: env.REPO,
                                 sha: "${sha}",
                                 context: env.PIPELINE_NAME,
                                 status: 'FAILURE',
                                 description: 'Pipeline failed ❌'
                }
            }
        }
    }
}