---
apiVersion: v1
kind: Namespace
metadata:
  name: nexus

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      securityContext:
        runAsUser: 200
        runAsGroup: 200
        fsGroup: 200
      containers:
        - name: nexus
          imagePullPolicy: Always
          image: sonatype/nexus3:latest
          ports:
            - containerPort: 8081
            - containerPort: 5000
          volumeMounts:
            - name: nexus-data
              mountPath: /opt/sonatype/sonatype-work
      volumes:
        - name: nexus-data
          hostPath:
            path: /mnt/core_data/k3s/nexus/
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nexus
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 32081
    - name: docker
      port: 5000
      targetPort: 5000
      nodePort: 32501

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus
  namespace: nexus
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: nexus.k3s.ravnet
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus
                port:
                  number: 8081

    - host: nexus.ravcube.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus
                port:
                  number: 8081

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-docker-registry
  namespace: nexus
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: docker.nexus.k3s.ravnet
      http:
        paths:
          - path: /v2/
            pathType: Prefix
            backend:
              service:
                name: nexus
                port:
                  number: 5000

    - host: docker.nexus.ravcube.com
      http:
        paths:
          - path: /v2/
            pathType: Prefix
            backend:
              service:
                name: nexus
                port:
                  number: 5000