{
  "name": "jenkins",
  "namespace": "jenkins",
  "replicas": 1,
  "image": {
    "repository": "jenkins/jenkins",
    "tag": "lts-jdk17",
    "pullPolicy": "IfNotPresent"
  },
  "service": {
    "type": "ClusterIP"
  },
  "ports": [
    8080,
    50000
  ],
  "servicePorts": [
    {
      "name": "web",
      "port": 8080,
      "targetPort": 8080
    },
    {
      "name": "agent",
      "port": 50000,
      "targetPort": 50000
    }
  ],
  "containerPorts": [
    {
      "containerPort": 8080,
      "protocol": "TCP"
    },
    {
      "containerPort": 50000,
      "protocol": "TCP"
    }
  ],
  "env": [
    {
      "name": "TZ",
      "value": "Europe/Warsaw"
    }
  ],
  "runAsUser": 0,
  "volumes": [
    {
      "name": "data",
      "hostPath": "/mnt/core_data/jenkins",
      "mountPath": "/var/jenkins_home"
    }
  ],
  "hostNetwork": false,
  "configMounts": [],
  "configMaps": [],
  "ingress": {
    "hosts": []
  },
  "secrets": {
    "enabled": false,
    "name": "jenkins-secrets"
  }
}
