version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /mnt/core_data/docker/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock