name: nexus
namespace: nexus
replicas: 1

image:
  repository: sonatype/nexus3
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP

ports:
  - 8081
  - 5000

runAsUser: 200

env:
  - name: TZ
    value: Europe/Warsaw

volumes:
  - name: nexus-data
    hostPath: /mnt/core_data/docker/nexus
    mountPath: /opt/sonatype/sonatype-work

ingress:
  hosts:
    - domain: nexus.ravcube.com
      port: 8081
